networks:
  laravel102:
    driver: bridge
services:
  nginx:
    image: nginx:alpine
    container_name: laravel102_nginx
    restart: unless-stopped
    tty: true
    environment:
      - NGINX_APP_HOST=${APP_DOMAIN_NAME}
    ports:
      - "18002:8001"
      - "18802:80"
    volumes:
      - ../src:/var/www/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../.docker_configs/certs:/etc/nginx/certs
    depends_on:
      - php
      - mysql
    networks:
      - laravel102
  redis:
    image: redis
    container_name: laravel102_redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=password
      - REDIS_REPLICATION_mode=master
    ports:
      - "15802:6379"
    networks:
      - laravel102
  redisinsight:
    image: redislabs/redisinsight
    container_name: laravel102_redisinsight
    restart: unless-stopped
    volumes:
      - ../redis:/var/lib/redis
    ports:
      - "15902:8001"
    networks:
      - laravel102
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel102_phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: LNIBsCP9Gj7xF4d3
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 10714741824
      MEMORY_LIMIT: 2G
      # MAX_EXECUTION_TIME: 600
    volumes:
      - ./configs/custom.config.inc.php:/etc/phpmyadmin/config.user.inc.php
    ports:
      - "18102:80"
    networks:
      - laravel102

  mysql:
    image: mysql:8.2
    container_name: laravel102_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "17102:3306"
    volumes:
      - ../mysql:/var/lib/mysql
    # user: 1000:1000
    environment:
      MYSQL_ROOT_PASSWORD: LNIBsCP9Gj7xF4d3
      MYSQL_DATABASE: laravel
      MYSQL_USER: tlc_app_2
      MYSQL_PASSWORD: DLTedTfrVzYbrYv9
    networks:
      - laravel102
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel102_php
    restart: unless-stopped
    tty: true
    working_dir: /var/www/app
    volumes:
      - ../src:/var/www/app
    ports:
      - "19002:9000"
    networks:
      - laravel102
