<?php

namespace App\Http\Controllers\ComponentDemo;

trait TraitDemoPivotTable
{
    function getPivotTableColumns2()
    {
        return [
            ['dataIndex' => "category"],
            ['dataIndex' => "product"],
            ['dataIndex' => "date"],
            ['dataIndex' => "price"],
            ['dataIndex' => "discount"],
            ['dataIndex' => "amount"],
        ];
    }
    function getPivotTableDataSource2()
    {
        $dataSource = [
            ["category" => "computer", "product" => "MacMini", "date" => "2024-01-01", "price" => 1000, "discount" => 10, "amount" => 990],
            ["category" => "computer", "product" => "MacBook", "date" => "2024-01-01", "price" => 2000, "discount" => 20, "amount" => 1980],
            ["category" => "computer", "product" => "iMac", "date" => "2024-01-01", "price" => 2500, "discount" => 25, "amount" => 2475],
            ["category" => "phone", "product" => "iPhone", "date" => "2024-01-01", "price" => 1200, "discount" => 12, "amount" => 1188],
            ["category" => "phone", "product" => "iPad", "date" => "2024-01-01", "price" => 1000, "discount" => 10, "amount" => 990],
            ["category" => "computer", "product" => "MacMini", "date" => "2024-01-02", "price" => 1000, "discount" => 0, "amount" => 1000],
            ["category" => "computer", "product" => "MacBook", "date" => "2024-01-03", "price" => 2000, "discount" => 0, "amount" => 2000],
            ["category" => "computer", "product" => "iMac", "date" => "2024-01-04", "price" => 2500, "discount" => 0, "amount" => 2500],
            ["category" => "phone", "product" => "iPhone", "date" => "2024-01-05", "price" => 1200, "discount" => 0, "amount" => 1200],
            ["category" => "phone", "product" => "iPad", "date" => "2024-01-06", "price" => 1000, "discount" => 0, "amount" => 1000],

        ];
        return $dataSource;
    }
    function getPivotTableColumns1()
    {
        return [
            ['dataIndex' => "time_sheet_start_time"],
            ['dataIndex' => "time_sheet_start_time_otr"],
            ['dataIndex' => "time_sheet_start_time_wfh"],
            ['dataIndex' => "time_sheet_hours"],
            ['dataIndex' => "time_sheet_hours_otr"],
            ['dataIndex' => "time_sheet_hours_wfh"],
            // ['dataIndex' => "time_sheet_mins"],
            ['dataIndex' => "sub_project_id"],
            ['dataIndex' => "user_id"],
            ['dataIndex' => "discipline_id"],
            ['dataIndex' => "lod_id"],
            ['dataIndex' => "pj_task_id"],
            ['dataIndex' => "workplace_id"],
            ['dataIndex' => "type_id"],
            ['dataIndex' => "department_id"],
            ['dataIndex' => "category_id"],
            ['dataIndex' => "staff_id"],
        ];
    }
    function getPivotTableDataSource1()
    {
        $dataSource = [
            [
                "time_sheet_start_time" => "2022-10-18",
                "time_sheet_start_time_otr" => "2022-10-18",
                "time_sheet_start_time_wfh" => "2022-10-18",
                "time_sheet_hours" => 8,
                "time_sheet_hours_otr" => 2,
                "time_sheet_hours_wfh" => 3,
                "time_sheet_mins" => 600,
                "sub_project_id" => 82,
                "user_id" => 26,
                "discipline_id" => 45,
                "lod_id" => 228,
                "pj_task_id" => 57,
                "workplace_id" => 4,
                "type_id" => 2,
                "department_id" => 7,
                "category_id" => 3,
                "staff_id" => "TLCM01219",
            ],
            [
                "time_sheet_start_time" => "2022-10-19",
                "time_sheet_start_time_otr" => "2022-10-19",
                "time_sheet_start_time_wfh" => "2022-10-19",
                "time_sheet_hours" => 8.0,
                "time_sheet_hours_otr" => 2,
                "time_sheet_hours_wfh" => 5,
                "time_sheet_mins" => 480,
                "sub_project_id" => 21,
                "user_id" => 26,
                "discipline_id" => 45,
                "lod_id" => 228,
                "pj_task_id" => 57,
                "workplace_id" => 4,
                "type_id" => 2,
                "department_id" => 7,
                "category_id" => 3,
                "staff_id" => "TLCM01071",
            ],
            [
                "time_sheet_start_time" => "2022-10-20",
                "time_sheet_start_time_otr" => "2022-10-20",
                "time_sheet_start_time_wfh" => "2022-10-20",
                "time_sheet_hours" => 8.0,
                "time_sheet_hours_otr" => 2,
                "time_sheet_hours_wfh" => 7,
                "time_sheet_mins" => 480,
                "sub_project_id" => 82,
                "user_id" => 26,
                "discipline_id" => 45,
                "lod_id" => 228,
                "pj_task_id" => 57,
                "workplace_id" => 4,
                "type_id" => 2,
                "department_id" => 7,
                "category_id" => 3,
                "staff_id" => "TLCM01071",
            ],
            [
                "time_sheet_start_time" => "2022-10-03",
                "time_sheet_start_time_otr" => "2022-10-03",
                "time_sheet_start_time_wfh" => "2022-10-03",
                "time_sheet_hours" => 8.0,
                "time_sheet_hours_otr" => 3,
                "time_sheet_hours_wfh" => 5,
                "time_sheet_mins" => 480,
                "sub_project_id" => 21,
                "user_id" => 26,
                "discipline_id" => 45,
                "lod_id" => 228,
                "pj_task_id" => 57,
                "workplace_id" => 4,
                "type_id" => 2,
                "department_id" => 7,
                "category_id" => 3,
                "staff_id" => "TLCM01071",
            ],
            [
                "time_sheet_start_time" => "2022-11-28",
                "time_sheet_start_time_otr" => "2022-11-28",
                "time_sheet_start_time_wfh" => "2022-11-28",
                "time_sheet_hours" => 7.5,
                "time_sheet_hours_otr" => 6,
                "time_sheet_hours_wfh" => 7.5,
                "time_sheet_mins" => 450,
                "sub_project_id" => 82,
                "user_id" => 49,
                "discipline_id" => 16,
                "lod_id" => 228,
                "pj_task_id" => 207,
                "workplace_id" => 1,
                "type_id" => 2,
                "department_id" => 8,
                "category_id" => 24,
                "staff_id" => "TLCM01060",
            ],
            [
                "time_sheet_start_time" => "2022-11-29",
                "time_sheet_start_time_otr" => "2022-11-29",
                "time_sheet_start_time_wfh" => "2022-11-29",
                "time_sheet_hours" => 8.5,
                "time_sheet_hours_otr" => 1.5,
                "time_sheet_hours_wfh" => 5,
                "time_sheet_mins" => 510,
                "sub_project_id" => 82,
                "user_id" => 49,
                "discipline_id" => 16,
                "lod_id" => 228,
                "pj_task_id" => 207,
                "workplace_id" => 1,
                "type_id" => 2,
                "department_id" => 8,
                "category_id" => 24,
                "staff_id" => "TLCM01060",
            ],
            [
                "time_sheet_start_time" => "2022-11-30",
                "time_sheet_start_time_otr" => "2022-11-30",
                "time_sheet_start_time_wfh" => "2022-11-30",
                "time_sheet_hours" => 3,
                "time_sheet_hours_otr" => 4,
                "time_sheet_hours_wfh" => 3,
                "time_sheet_mins" => 180,
                "sub_project_id" => 82,
                "user_id" => 49,
                "discipline_id" => 16,
                "lod_id" => 228,
                "pj_task_id" => 207,
                "workplace_id" => 1,
                "type_id" => 2,
                "department_id" => 8,
                "category_id" => 24,
                "staff_id" => "TLCM01060",
            ],
            [
                "time_sheet_start_time" => "2022-11-14",
                "time_sheet_start_time_otr" => "2022-11-14",
                "time_sheet_start_time_wfh" => "2022-11-14",
                "time_sheet_hours" => 8,
                "time_sheet_hours_otr" => 7,
                "time_sheet_hours_wfh" => 3,
                "time_sheet_mins" => 480,
                "sub_project_id" => 82,
                "user_id" => 506,
                "discipline_id" => 15,
                "lod_id" => 228,
                "pj_task_id" => 61,
                "workplace_id" => 4,
                "type_id" => 1,
                "department_id" => 7,
                "category_id" => 3,
                "staff_id" => "TLCM01219",
            ],
            [
                "time_sheet_start_time" => "2022-11-15",
                "time_sheet_start_time_otr" => "2022-11-15",
                "time_sheet_start_time_wfh" => "2022-11-15",
                "time_sheet_hours" => 8,
                "time_sheet_hours_otr" => 1,
                "time_sheet_hours_wfh" => 2,
                "time_sheet_mins" => 480,
                "sub_project_id" => 82,
                "user_id" => 506,
                "discipline_id" => 15,
                "lod_id" => 228,
                "pj_task_id" => 61,
                "workplace_id" => 4,
                "type_id" => 1,
                "department_id" => 7,
                "category_id" => 3,
                "staff_id" => "TLCM01219",
            ],
            [
                "time_sheet_start_time" => "2022-11-16",
                "time_sheet_start_time_otr" => "2022-11-16",
                "time_sheet_start_time_wfh" => "2022-11-16",
                "time_sheet_hours" => 5,
                "time_sheet_hours_otr" => 1,
                "time_sheet_hours_wfh" => 2,
                "time_sheet_mins" => 480,
                "sub_project_id" => 82,
                "user_id" => 506,
                "discipline_id" => 15,
                "lod_id" => 228,
                "pj_task_id" => 61,
                "workplace_id" => 4,
                "type_id" => 1,
                "department_id" => 7,
                "category_id" => 3,
                "staff_id" => "TLCM01219",
            ]

        ];
        return $dataSource;
    }
}
