version: '3'

networks:
    laravel202:
        driver: bridge

services:
    nginx:
        image: nginx:alpine
        container_name: laravel202_nginx
        restart: unless-stopped
        tty: true
        ports:
            - "28002:8001"
        volumes:
            - ./src:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel202
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel202_phpmyadmin
        restart: unless-stopped
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        ports:
            - 28102:80
        networks:
            - laravel202

    mysql:
        image: mysql
        container_name: laravel202_mysql
        restart: unless-stopped
        tty: true
        ports:
            - "23302:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        networks:
            - laravel202

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel202_php
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes:
            - ./src:/var/www/app
        ports:
            - "29002:9000"
        networks:
            - laravel202
