version: "3.8"
services:
  webserver:
    # image: nginx
    build: .
    restart: always
    ports:
      - "443:443" # wp ----> wordpress
    volumes:
      - ./log:/var/log/nginx
      - ../.docker_configs/certs:/etc/ssl/certs
networks:
  webserver:
