# FROM php:8.0-fpm-alpine
FROM php:8.2-fpm-alpine3.17

WORKDIR /var/www/app

RUN apk update && apk add \
    # build-base shadow supervisor \
    curl \
    libzip-dev \
    libpng-dev \
    libxml2-dev \
    freetype-dev \
    libjpeg-turbo-dev \
    zip \
    unzip \
    # ca-certificates \
    # openssl \
    nano \
    mc \
    htop \
    supervisor \
    php-zip

RUN curl -sSLf \
    -o /usr/local/bin/install-php-extensions \
    https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions && \
    chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions ldap 
RUN docker-php-ext-install pdo pdo_mysql 
# \
# && apk --no-cache add nodejs npm

RUN docker-php-ext-install gd && \
    docker-php-ext-configure gd --with-freetype --with-jpeg && \
    docker-php-ext-install -j$(nproc) gd

RUN docker-php-ext-install zip

RUN docker-php-ext-install pcntl

RUN apk add build-base autoconf
RUN pecl install apcu 

RUN apk add nodejs npm
# RUN apk add -- no-cache gconf
# Create a symbolic link to make node and npm commands available in /usr/local/bin
RUN ln -s /usr/bin/node /usr/local/bin/node
RUN ln -s /usr/bin/npm /usr/local/bin/npm
RUN apk add --no-cache \
    chromium \
    chromium-chromedriver
RUN apk update && apk add --no-cache libgcc libstdc++ nss wget git 
RUN npm install --location=global --unsafe-perm puppeteer@^17
RUN chmod -R o+rx /usr/local/lib/node_modules/puppeteer/.local-chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true 
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

COPY ./configs/php.ini /usr/local/etc/php/

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

# RUN apk add unixodbc-dev
# RUN pecl install pdo_sqlsrv sqlsrv

COPY ./supervisord.conf /etc/supervisord.conf
COPY ./supervisor.d /etc/supervisor.d

RUN addgroup -g 1000 ndcgp
RUN adduser -D -u 1000 ndc -G ndcgp
# run this line manually by root accout
RUN chown -R ndc:ndcgp /var/www/app
USER ndc

# RUN usermod -u 1000 www-data

# RUN chown -R www-data:www-data .

# ENV ENABLE_CRONTAB 1
# ENV ENABLE_HORIZON 1
# COPY ./docker-entrypoint.sh /var/www/app/docker-entrypoint.sh
# RUN chmod +x /var/www/app/docker-entrypoint.sh
# ENTRYPOINT ["sh", "/var/www/app/docker-entrypoint.sh"]

# CMD ["supervisord -n -c /etc/supervisord.conf"]

#RUN rm -rf /var/cache/apk/*