<?php

namespace App\Http\Controllers;

class WelcomeFortuneDataSource02
{
    function getDataSource()
    {
        $columns = [

            ['dataIndex' => 'action', 'renderer' => 'action_column', 'fixed' => 'left'],
            ['dataIndex' => 'name', 'width' => 200, 'fixed' => 'left'],
            ['dataIndex' => 'hidden_column', 'invisible' => true, 'fixed' => 'left'],
            ['dataIndex' => 'status', 'subTitle' => 'fixed-left no-bg', 'fixed' => 'left-no-bg', 'footer' => 'agg_none',],
            ['dataIndex' => 'agg_none', 'subTitle' => 'int / float', 'align' => 'right', 'footer' => 'agg_none', 'fixed' => 'left'],
            ['dataIndex' => 'agg_count_all', 'subTitle' => 'int / float', 'align' => 'right', 'footer' => 'agg_count_all'],
            ['dataIndex' => 'agg_sum', 'subTitle' => 'int / float', 'align' => 'right', 'footer' => 'agg_sum'],
            ['dataIndex' => 'agg_avg', 'subTitle' => 'int / float', 'align' => 'right', 'footer' => 'agg_avg'],
            ['dataIndex' => 'agg_median', 'subTitle' => 'int / float', 'align' => 'right', 'footer' => 'agg_median'],
            ['dataIndex' => 'agg_min', 'subTitle' => 'int / float', 'align' => 'right', 'footer' => 'agg_min'],
            ['dataIndex' => 'agg_max', 'subTitle' => 'int / float', 'align' => 'right', 'footer' => 'agg_max'],
            ['dataIndex' => 'agg_range', 'subTitle' => 'int / float', 'align' => 'right', 'footer' => 'agg_range'],
            ['dataIndex' => 'agg_count_unique_values', 'subTitle' => 'int / float', 'align' => 'right', 'footer' => 'agg_count_unique_values'],
            ['dataIndex' => 'agg_unique_values', 'subTitle' => 'int / float', 'align' => 'right', 'footer' => 'agg_unique_values'],
            // ['dataIndex' => 'status', 'subTitle' => 'fixed-right no-bg', 'fixed' => 'right-no-bg', 'footer' => 'agg_none',],
            ['dataIndex' => 'text', 'subTitle' => 'a string', 'fixed' => 'right'],
            ['dataIndex' => 'date', 'subTitle' => 'a date', 'fixed' => 'right', 'width' => 120],
        ];
        $sndHeader = [
            // 'name' => 'Line 1',
            'hidden_column' => 'hidden',
            'agg_none' => 'a',
            'agg_count_all' => 'b',
            'agg_sum' => 'c',
            'agg_avg' => 'd',
            'agg_median' => 'e',
            'agg_min' => 'f',
            'agg_max' => 'g',
            'agg_range' => 'h',
            'agg_count_unique_values' => 'i',
            'agg_unique_values' => 'j',
            'text' => 'k',
            'date' => 'l',
        ];
        $tables = [
            [
                'name' => 'Line 1',
                'hidden_column' => 'hidden',
                'status' => [
                    'value' => '<i class="fa-regular fa-circle-plus text-lg"></i>',
                    'cell_href' => 'https://www.google.com',
                    'cell_class' => 'bg-green-300 text-red-500',
                    'cell_title' => 'Create a new item 111',
                    'cell_div_class' => 'p-2 w-11',
                ],
                'agg_none' => 1,
                'agg_count_all' => 1,
                'agg_sum' => 1,
                'agg_avg' => 1,
                'agg_median' => 1,
                'agg_min' => 1,
                'agg_max' => 1,
                'agg_range' => 1,
                'agg_count_unique_values' => 1,
                'agg_unique_values' => 1,
                'text' => 'text',
                'date' => '2021-01-01',
            ],
            [
                'name' => 'Line 2',
                'hidden_column' => 'hidden',
                'status' => [
                    'value' => '<i class="fa-regular fa-circle-plus text-lg"></i>',
                    'cell_href' => 'https://www.google.com',
                    'cell_class' => 'bg-green-300 text-red-500',
                    'cell_title' => 'Create a new item 111',
                    'cell_div_class' => 'p-2 w-11',
                ],
                'agg_none' => 2,
                'agg_count_all' => 2,
                'agg_sum' => 2,
                'agg_avg' => 2,
                'agg_median' => 2,
                'agg_min' => 2,
                'agg_max' => 2,
                'agg_range' => 2,
                'agg_count_unique_values' => 2,
                'agg_unique_values' => 2,
                'text' => 'text',
                'date' => '2021-01-02',
            ],
            [
                'name' => 'Line 3',
                'hidden_column' => 'hidden',
                'status' => [
                    'value' => '<i class="fa-regular fa-circle-plus text-lg"></i>',
                    'cell_href' => 'https://www.google.com',
                    'cell_class' => 'bg-green-300 text-red-500',
                    'cell_title' => 'Create a new item 111',
                    'cell_div_class' => 'p-2 w-11',
                ],
                'agg_none' => 3,
                'agg_count_all' => 3,
                'agg_sum' => 3,
                'agg_avg' => 3,
                'agg_median' => 3,
                'agg_min' => 3,
                'agg_max' => 3,
                'agg_range' => 3,
                'agg_count_unique_values' => 3,
                'agg_unique_values' => 3,
                'text' => 'text',
                'date' => '2021-01-03',
            ],
            [
                'name' => 'Line 4',
                'hidden_column' => 'hidden',
                'status' => [
                    'value' => '<i class="fa-regular fa-circle-plus text-lg"></i>',
                    'cell_href' => 'https://www.google.com',
                    'cell_class' => 'bg-green-300 text-red-500',
                    'cell_title' => 'Create a new item 111',
                    'cell_div_class' => 'p-2 w-11',
                ],
                'agg_none' => 4,
                'agg_count_all' => 4,
                'agg_sum' => 4,
                'agg_avg' => 4,
                'agg_median' => 4,
                'agg_min' => 4,
                'agg_max' => 4,
                'agg_range' => 4,
                'agg_count_unique_values' => 4,
                'agg_unique_values' => 4,
                'text' => 'text',
                'date' => '2021-01-04',
            ],
            [
                'name' => 'Line 5',
                'hidden_column' => 'hidden',
                'status' => [
                    'value' => '<i class="fa-regular fa-circle-plus text-lg"></i>',
                    'cell_href' => 'https://www.google.com',
                    'cell_class' => 'bg-green-300 text-red-500',
                    'cell_title' => 'Create a new item 111',
                    'cell_div_class' => 'p-2 w-11',
                ],
                'agg_none' => 5,
                'agg_count_all' => 5,
                'agg_sum' => 5,
                'agg_avg' => 5,
                'agg_median' => 5,
                'agg_min' => 5,
                'agg_max' => 5,
                'agg_range' => 5,
                'agg_count_unique_values' => 5,
                'agg_unique_values' => 5,
                'text' => 'text',
                'date' => '2021-01-05',
            ],
            [
                'name' => 'Line 6',
                'hidden_column' => 'hidden',
                'status' => [
                    'value' => '<i class="fa-regular fa-circle-plus text-lg"></i>',
                    'cell_href' => 'https://www.google.com',
                    'cell_class' => 'bg-green-300 text-red-500',
                    'cell_title' => 'Create a new item 111',
                    'cell_div_class' => 'p-2 w-11',
                ],
                'agg_none' => 6,
                'agg_count_all' => 6,
                'agg_sum' => 6,
                'agg_avg' => 6,
                'agg_median' => 6,
                'agg_min' => 6,
                'agg_max' => 6,
                'agg_range' => 6,
                'agg_count_unique_values' => 6,
                'agg_unique_values' => 6,
                'text' => 'text',
                'date' => '2021-01-06',
            ],
            [
                'name' => 'Line 7',
                'hidden_column' => 'hidden',
                'status' => [
                    'value' => '<i class="fa-regular fa-circle-plus text-lg"></i>',
                    'cell_href' => 'https://www.google.com',
                    'cell_class' => 'bg-green-300 text-red-500',
                    'cell_title' => 'Create a new item 111',
                    'cell_div_class' => 'p-2 w-11',
                ],
                'agg_none' => 7,
                'agg_count_all' => 7,
                'agg_sum' => 7,
                'agg_avg' => 7,
                'agg_median' => 7,
                'agg_min' => 7,
                'agg_max' => 7,
                'agg_range' => 7,
                'agg_count_unique_values' => 7,
                'agg_unique_values' => 7,
                'text' => 'text',
                'date' => '2021-01-07',
            ],
            [
                'name' => 'Line 8',
                'hidden_column' => 'hidden',
                'status' => [
                    'value' => '<i class="fa-regular fa-circle-plus text-lg"></i>',
                    'cell_href' => 'https://www.google.com',
                    'cell_class' => 'bg-green-300 text-red-500',
                    'cell_title' => 'Create a new item 111',
                    'cell_div_class' => 'p-2 w-11',
                ],
                'agg_none' => 8,
                'agg_count_all' => 8,
                'agg_sum' => 8,
                'agg_avg' => 8,
                'agg_median' => 8,
                'agg_min' => 8,
                'agg_max' => 8,
                'agg_range' => 8,
                'agg_count_unique_values' => 8,
                'agg_unique_values' => 8,
                'text' => 'text',
                'date' => '2021-01-08',
            ],
            [
                'name' => 'Line 9',
                'hidden_column' => 'hidden',
                'status' => [
                    'value' => '<i class="fa-regular fa-circle-plus text-lg"></i>',
                    'cell_href' => 'https://www.google.com',
                    'cell_class' => 'bg-green-300 text-red-500',
                    'cell_title' => 'Create a new item 111',
                    'cell_div_class' => 'p-2 w-11',
                ],
                'agg_none' => 9,
                'agg_count_all' => 9,
                'agg_sum' => 9,
                'agg_avg' => 9,
                'agg_median' => 9,
                'agg_min' => 9,
                'agg_max' => 9,
                'agg_range' => 9,
                'agg_count_unique_values' => 9,
                'agg_unique_values' => 9,
                'text' => 'text',
                'date' => '2021-01-09',
            ],
        ];

        return  [
            'columns' => $columns,
            'dataSource' => $tables,
            'sndHeader' => $sndHeader,
        ];
    }
}
