version: "3"

networks:
  laravel202:
    driver: bridge
services:
  nginx:
    image: nginx:alpine
    container_name: laravel202_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "28002:8001"
    environment:
      - NGINX_APP_HOST=${APP_DOMAIN_NAME}
    volumes:
      - ../src:/var/www/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./configs/certs:/etc/nginx/certs
    depends_on:
      - php
      - mysql
    networks:
      - laravel202
  redis:
    image: redis
    container_name: laravel202_redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=password
      - REDIS_REPLICATION_mode=master
    ports:
      - "27912:6379"
    networks:
      - laravel202
  redisinsight:
    image: redislabs/redisinsight
    container_name: laravel202_redisinsight
    restart: unless-stopped
    volumes:
      - ../redis:/var/lib/redis
    ports:
      - "27902:8001"
    networks:
      - laravel202
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel202_phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: LNIBsCP9Gj7xF4d3
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "28102:80"
    networks:
      - laravel202

  mysql:
    image: mysql
    container_name: laravel202_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "28302:3306"
    volumes:
      - ../mysql:/var/lib/mysql
    # user: 1000:1000
    environment:
      MYSQL_ROOT_PASSWORD: LNIBsCP9Gj7xF4d3
      MYSQL_DATABASE: laravel
      MYSQL_USER: tlc_app_2
      MYSQL_PASSWORD: DLTedTfrVzYbrYv9
    networks:
      - laravel202

  websocket:
    container_name: laravel202_websocket
    build:
      context: ./laravel-echo-server
      dockerfile: Dockerfile
    volumes:
      - ../src/.env:/var/www/websocket/.env
    restart: unless-stopped

    ports:
      - "6001"
    depends_on:
      - nginx
      - redis
    networks:
      - laravel202
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel202_php
    restart: unless-stopped
    tty: true
    working_dir: /var/www/app
    volumes:
      - ../src:/var/www/app
    ports:
      - "29002:9000"
    networks:
      - laravel202
