version: "3.8"
services:
  webserver:
    # image: nginx
    build: .
    restart: always
    ports:
      - "80:80" # wp ----> wordpress
    volumes:
      - ./log:/var/log/nginx
networks:
  webserver:
