version: "3"

networks:
  websockets:
    driver: bridge
services:
  nginx:
    image: nginx:alpine
    container_name: websockets_nginx
    restart: unless-stopped
    tty: true
    environment:
      - NGINX_APP_HOST=${APP_DOMAIN_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../.docker_configs/certs:/etc/nginx/certs
    networks:
      - websockets
  websockets:
    container_name: websockets
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "6001:6001"
    networks:
      - laravel_websockets
