version: "3"

networks:
  ws:
    driver: bridge
services:
  redis:
    image: redis
    container_name: websockets_redis
    # restart: unless-stopped
    environment:
      - REDIS_PASSWORD=password
      - REDIS_REPLICATION_mode=master
    ports:
      - "6379:6379"
    networks:
      - ws
  soketi:
    image: "quay.io/soketi/soketi:latest-16-alpine"
    container_name: websockets_soketi
    environment:
      SOKETI_DEBUG: "1"
      SOKETI_METRICS_SERVER_PORT: "9601"
      SOKETI_DEFAULT_APP_ID: "tlc-id"
      SOKETI_DEFAULT_APP_KEY: "tlc-key"
      SOKETI_DEFAULT_APP_SECRET: "tlc-secret"
      # SOKETI_SSL_CERT: "/path/to/certs/public.crt"
      # SOKETI_SSL_KEY: "/path/to/certs/private.key"
      # volumes:
      # - ../.docker_configs/certs:/path/to/certs
    ports:
      - "6001:6001"
      - "9601:9601"
    networks:
      - ws
  nginx:
    image: nginx:alpine
    container_name: websockets_nginx
    restart: unless-stopped
    tty: true
    environment:
      - NGINX_WEBSOCKET_HOST=${WEBSOCKET_DOMAIN_NAME}
    ports:
      - "6002:6002"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../.docker_configs/certs:/etc/nginx/certs
    networks:
      - ws
    depends_on:
      - soketi
