version: "3"

networks:
  ws:
    driver: bridge
services:
  nginx:
    image: nginx:alpine
    container_name: websockets_nginx
    restart: unless-stopped
    tty: true
    environment:
      - NGINX_WEBSOCKET_HOST=${WEBSOCKET_DOMAIN_NAME}
    ports:
      - "36102:6001"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../.docker_configs/certs:/etc/nginx/certs
    networks:
      - ws
  redis:
    image: redis
    container_name: websockets_redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=password
      - REDIS_REPLICATION_mode=master
    ports:
      - "6379"
    networks:
      - ws
  websockets:
    container_name: websockets
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "6001:6001"
    volumes:
      - ../src:/var/www/html
    networks:
      - ws
  # soketi:
  #   image: "quay.io/soketi/soketi:latest-16-alpine"
  #   container_name: websockets_soketi
  #   environment:
  #     SOKETI_DEBUG: "1"
  #     SOKETI_METRICS_SERVER_PORT: "9601"
  #   ports:
  #     - "${SOKETI_PORT:-6001}:6001"
  #     - "${SOKETI_METRICS_SERVER_PORT:-9601}:9601"
  #   networks:
  #     - ws
